/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import regraNegocio.ClienteRN;
import regraNegocio.PedidoRN;
import vo.ClienteVO;
import vo.PedidoItemVO;
import vo.PedidoVO;

/**
 *
 * @author Giovane
 */
public class FormPedido extends javax.swing.JFrame {

    /**
     * Creates new form FormPedidos
     */
    public FormPedido() {
        initComponents();
        tValorTotal.setText("0.0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNorte = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lTelefone = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JFormattedTextField();
        bPesquisar = new javax.swing.JButton();
        bCadastrar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        tStatus = new javax.swing.JTextField();
        Status = new javax.swing.JLabel();
        tComplemento = new javax.swing.JTextField();
        lComplemento = new javax.swing.JLabel();
        tNumero = new javax.swing.JTextField();
        lNumero = new javax.swing.JLabel();
        tLogradouro = new javax.swing.JTextField();
        lLogradouro = new javax.swing.JLabel();
        lCodigo = new javax.swing.JLabel();
        tCodigo = new javax.swing.JTextField();
        lNome = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        lCidade = new javax.swing.JLabel();
        tCidade = new javax.swing.JTextField();
        lEstado = new javax.swing.JLabel();
        tEstado = new javax.swing.JTextField();
        lBairro = new javax.swing.JLabel();
        tBairro = new javax.swing.JTextField();
        lCep = new javax.swing.JLabel();
        tfCep = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        pSul = new javax.swing.JPanel();
        bFinalizarPedido = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        pCentro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bAddPizza = new javax.swing.JButton();
        bAddSabor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItens = new javax.swing.JTable();
        lValorTotal = new javax.swing.JLabel();
        tValorTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedidos");

        lTelefone.setText("Telefone:");

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bPesquisar.setText("Pesquisar");
        bPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesquisarActionPerformed(evt);
            }
        });

        bCadastrar.setText("Cadastrar Novo");
        bCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarActionPerformed(evt);
            }
        });

        bEditar.setText("Editar Cliente");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        tStatus.setEditable(false);
        tStatus.setEnabled(false);

        Status.setText("Status:");

        tComplemento.setEditable(false);
        tComplemento.setEnabled(false);

        lComplemento.setText("Complemento:");

        tNumero.setEditable(false);
        tNumero.setEnabled(false);

        lNumero.setText("Número:");

        tLogradouro.setEditable(false);
        tLogradouro.setEnabled(false);

        lLogradouro.setText("Logradouro:");

        lCodigo.setText("Código:");

        tCodigo.setEditable(false);
        tCodigo.setEnabled(false);

        lNome.setText("Nome:");

        tNome.setEditable(false);
        tNome.setEnabled(false);

        lCidade.setText("Cidade:");

        tCidade.setEditable(false);
        tCidade.setEnabled(false);

        lEstado.setText("Estado:");

        tEstado.setEditable(false);
        tEstado.setEnabled(false);

        lBairro.setText("Bairro:");

        tBairro.setEditable(false);
        tBairro.setEnabled(false);

        lCep.setText("CEP:");

        tfCep.setEditable(false);
        try {
            tfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCep.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Dados do Cliente");

        javax.swing.GroupLayout pNorteLayout = new javax.swing.GroupLayout(pNorte);
        pNorte.setLayout(pNorteLayout);
        pNorteLayout.setHorizontalGroup(
            pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pNorteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pNorteLayout.createSequentialGroup()
                        .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lLogradouro)
                            .addComponent(lCidade)
                            .addComponent(lCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pNorteLayout.createSequentialGroup()
                                .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(tLogradouro))
                                .addGap(241, 241, 241)
                                .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pNorteLayout.createSequentialGroup()
                                        .addComponent(lBairro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pNorteLayout.createSequentialGroup()
                                        .addComponent(lComplemento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pNorteLayout.createSequentialGroup()
                                .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(Status)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(lCep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1)
                    .addGroup(pNorteLayout.createSequentialGroup()
                        .addComponent(lTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCadastrar)
                        .addGap(173, 173, 173))
                    .addGroup(pNorteLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lEstado)
                            .addComponent(lNumero))
                        .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pNorteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pNorteLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(tEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pNorteLayout.setVerticalGroup(
            pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNorteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTelefone)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPesquisar)
                    .addComponent(bCadastrar)
                    .addComponent(bEditar))
                .addGap(18, 18, 18)
                .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lCep)
                        .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lCodigo)
                        .addComponent(lNome)
                        .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Status)
                        .addComponent(tStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBairro)
                    .addComponent(lCidade)
                    .addComponent(lEstado)
                    .addComponent(tCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLogradouro)
                    .addComponent(tLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumero)
                    .addComponent(tNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lComplemento)
                    .addComponent(tComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pNorte, java.awt.BorderLayout.NORTH);

        bFinalizarPedido.setText("Finalizar Pedido");
        bFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinalizarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSulLayout = new javax.swing.GroupLayout(pSul);
        pSul.setLayout(pSulLayout);
        pSulLayout.setHorizontalGroup(
            pSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSulLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(bFinalizarPedido)
                .addContainerGap(280, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pSulLayout.setVerticalGroup(
            pSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSulLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bFinalizarPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pSul, java.awt.BorderLayout.SOUTH);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Dados do Pedido");

        bAddPizza.setText("Adicionar Pizza");
        bAddPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddPizzaActionPerformed(evt);
            }
        });

        bAddSabor.setText("Adicionar Bebida");
        bAddSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddSaborActionPerformed(evt);
            }
        });

        tbItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Quantidade", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbItens);
        if (tbItens.getColumnModel().getColumnCount() > 0) {
            tbItens.getColumnModel().getColumn(0).setResizable(false);
            tbItens.getColumnModel().getColumn(2).setResizable(false);
            tbItens.getColumnModel().getColumn(3).setResizable(false);
        }

        lValorTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lValorTotal.setText("Valor Total:");

        tValorTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tValorTotal.setEnabled(false);

        javax.swing.GroupLayout pCentroLayout = new javax.swing.GroupLayout(pCentro);
        pCentro.setLayout(pCentroLayout);
        pCentroLayout.setHorizontalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCentroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAddPizza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAddSabor)
                .addGap(218, 218, 218))
            .addGroup(pCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addGroup(pCentroLayout.createSequentialGroup()
                        .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(pCentroLayout.createSequentialGroup()
                                .addComponent(lValorTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pCentroLayout.setVerticalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddPizza)
                    .addComponent(bAddSabor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lValorTotal)
                    .addComponent(tValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(pCentro, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void bFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinalizarPedidoActionPerformed
        if(!tCodigo.getText().isEmpty()){
            try{
                PedidoVO pedidoVO = new PedidoVO();
                pedidoVO.setCodigoCliente(Integer.parseInt(tCodigo.getText()));

                if(!tValorTotal.getText().equals("0.0")){
                    pedidoVO.setValorTotal(Double.parseDouble(tValorTotal.getText()));
                }else{
                    System.out.println("tratar nenhum item");
                }

                PedidoRN pedidoRN = new PedidoRN();
                int ultimoId = pedidoRN.gravarPedido(pedidoVO);
                
                PedidoItemVO pedidoItemVO = new PedidoItemVO();
                pedidoItemVO.setCodigoPedido(ultimoId);
                System.out.println("chegou"+ultimoId);
                
                javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tbItens.getModel();
                
                for(int i=0; i<dtm.getRowCount(); i++){
//                    for(int j=0; j<=dtm.getColumnCount(); j++){
                        pedidoItemVO.setCodigoProduto((int) dtm.getValueAt(i, 1));
                        pedidoItemVO.setDescricao((String) dtm.getValueAt(i, 2));
                        pedidoItemVO.setQuantidade((int) dtm.getValueAt(i, 3));
                        pedidoItemVO.setValorUnitario((Double) dtm.getValueAt(i, 4));
                        
                        System.out.println(pedidoItemVO.getCodigoPedido());
                        System.out.println(pedidoItemVO.getCodigoProduto());
                        pedidoRN.gravarPedidoItem(pedidoItemVO);
//                    }
                }
                
                
                
            }catch(SQLException sql){
                
            }catch(Exception e){
                
            }
        }else JOptionPane.showMessageDialog(null, "É necessário inserir um cliente para finalizar o pedido.", "Pedido", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bFinalizarPedidoActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        CFormCliente cFormCliente = new CFormCliente();
        cFormCliente.setVisible(true);
    }//GEN-LAST:event_bEditarActionPerformed

    private void bCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarActionPerformed
        CFormCliente cFormCliente = new CFormCliente();
        cFormCliente.setVisible(true);
    }//GEN-LAST:event_bCadastrarActionPerformed

    private void bPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisarActionPerformed
        try{
            if(!tfTelefone.getText().equals("(  )    -    ")){
                ClienteVO clienteVO = new ClienteVO();
                clienteVO.setTelefone(tfTelefone.getText());

                ClienteRN clienteRN = new ClienteRN();
                ArrayList<ClienteVO> cliente = clienteRN.buscarCliente(clienteVO);
                if(!cliente.isEmpty()){
                    for(ClienteVO cliVO: cliente){
                        tCodigo.setText(String.valueOf(cliVO.getCodigo()));
                        tNome.setText(cliVO.getNome());
                        tStatus.setText(cliVO.getStatus());
                        tfCep.setText(cliVO.getCep());
                        tCidade.setText(cliVO.getCidade());
                        tEstado.setText(cliVO.getEstado());
                        tBairro.setText(cliVO.getBairro());
                        tLogradouro.setText(cliVO.getLogradouro());
                        tNumero.setText(String.valueOf(cliVO.getNumero()));
                        tComplemento.setText(cliVO.getComplemento());
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Nenhum registro encontrado.", "Pesquisa de Cliente", JOptionPane.INFORMATION_MESSAGE);
                    tCodigo.setText("");
                    tNome.setText("");
                    tStatus.setText("");
                    tfCep.setText("");
                    tCidade.setText("");
                    tEstado.setText("");
                    tBairro.setText("");
                    tLogradouro.setText("");
                    tNumero.setText("");
                    tComplemento.setText("");
                }
            }else
                JOptionPane.showMessageDialog(null, "Informe um telefone e tente realizar a persquisa novamente.", "Pesquisa de Cliente", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException sql){
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_bPesquisarActionPerformed

    private void bAddPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddPizzaActionPerformed
        FormPedidoPizza formPedidoPizza = new FormPedidoPizza(this);
        formPedidoPizza.setVisible(true);
    }//GEN-LAST:event_bAddPizzaActionPerformed

    private void bAddSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddSaborActionPerformed
        FormPedidoBebida formPedidoBebida = new FormPedidoBebida(this);
        formPedidoBebida.setVisible(true);
        
    }//GEN-LAST:event_bAddSaborActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Status;
    private javax.swing.JButton bAddPizza;
    private javax.swing.JButton bAddSabor;
    private javax.swing.JButton bCadastrar;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bFinalizarPedido;
    private javax.swing.JButton bPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lBairro;
    private javax.swing.JLabel lCep;
    private javax.swing.JLabel lCidade;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lComplemento;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lLogradouro;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lTelefone;
    private javax.swing.JLabel lValorTotal;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pNorte;
    private javax.swing.JPanel pSul;
    private javax.swing.JTextField tBairro;
    private javax.swing.JTextField tCidade;
    private javax.swing.JTextField tCodigo;
    private javax.swing.JTextField tComplemento;
    private javax.swing.JTextField tEstado;
    private javax.swing.JTextField tLogradouro;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tNumero;
    private javax.swing.JTextField tStatus;
    protected javax.swing.JTextField tValorTotal;
    protected javax.swing.JTable tbItens;
    private javax.swing.JFormattedTextField tfCep;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
