/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import regraNegocio.BordaRN;
import regraNegocio.PizzaRN;
import vo.BordaVO;
import vo.PizzaVO;

/**
 *
 * @author Giovane
 */
public class FormPedidoPizza extends javax.swing.JFrame {

    /**
     * Creates new form FormPedidoPizza
     */
    FormPedido form;
    public FormPedidoPizza(FormPedido form) {
        initComponents();
        preencherCombo();
        this.form = form;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPedidoPizza = new javax.swing.JPanel();
        lTamanho = new javax.swing.JLabel();
        lBorda = new javax.swing.JLabel();
        lSabor1 = new javax.swing.JLabel();
        cbTamanho = new javax.swing.JComboBox<>();
        cbBorda = new javax.swing.JComboBox<>();
        lSabor2 = new javax.swing.JLabel();
        lSabor3 = new javax.swing.JLabel();
        cbSabor1 = new javax.swing.JComboBox<>();
        cbSabor2 = new javax.swing.JComboBox<>();
        cbSabor3 = new javax.swing.JComboBox<>();
        bAdicionar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Pizza");

        lTamanho.setText("Tamanho:");

        lBorda.setText("Borda:");

        lSabor1.setText("Sabor 1:");

        cbTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequena", "Média", "Grande" }));

        lSabor2.setText("Sabor 2:");

        lSabor3.setText("Sabor 3:");

        bAdicionar.setText("Adicionar");
        bAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdicionarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pPedidoPizzaLayout = new javax.swing.GroupLayout(pPedidoPizza);
        pPedidoPizza.setLayout(pPedidoPizzaLayout);
        pPedidoPizzaLayout.setHorizontalGroup(
            pPedidoPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPedidoPizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPedidoPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPedidoPizzaLayout.createSequentialGroup()
                        .addGroup(pPedidoPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pPedidoPizzaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bCancelar))
                            .addGroup(pPedidoPizzaLayout.createSequentialGroup()
                                .addComponent(lTamanho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(lBorda)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBorda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pPedidoPizzaLayout.createSequentialGroup()
                        .addGroup(pPedidoPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pPedidoPizzaLayout.createSequentialGroup()
                                .addComponent(lSabor3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSabor3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPedidoPizzaLayout.createSequentialGroup()
                                .addComponent(lSabor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSabor1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPedidoPizzaLayout.createSequentialGroup()
                                .addComponent(lSabor2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSabor2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pPedidoPizzaLayout.setVerticalGroup(
            pPedidoPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPedidoPizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPedidoPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTamanho)
                    .addComponent(lBorda)
                    .addComponent(cbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pPedidoPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSabor1)
                    .addComponent(cbSabor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pPedidoPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSabor2)
                    .addComponent(cbSabor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pPedidoPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSabor3)
                    .addComponent(cbSabor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pPedidoPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAdicionar)
                    .addComponent(bCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pPedidoPizza, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdicionarActionPerformed
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) this.form.tbItens.getModel();
        dtm.fireTableDataChanged();
        
        Double valorPizza = 0.0;
        String sabor1 = cbSabor1.getSelectedItem().equals("Selecione") ? "" : (String)cbSabor1.getSelectedItem();
        String sabor2 = cbSabor2.getSelectedItem().equals("Selecione") ? "" : (String)cbSabor2.getSelectedItem();
        String sabor3 = cbSabor3.getSelectedItem().equals("Selecione") ? "" : (String)cbSabor3.getSelectedItem();
        
        if(cbTamanho.getSelectedItem().equals("Pequena")){
            valorPizza = 15.0;
            this.form.tValorTotal.setText(String.valueOf(Double.parseDouble(this.form.tValorTotal.getText()) + valorPizza));
        }else if(cbTamanho.getSelectedItem().equals("Média")){
            valorPizza = 20.0;
            this.form.tValorTotal.setText(String.valueOf(Double.parseDouble(this.form.tValorTotal.getText()) + valorPizza));
        }else if(cbTamanho.getSelectedItem().equals("Grande")){
            valorPizza = 30.0;
            this.form.tValorTotal.setText(String.valueOf(Double.parseDouble(this.form.tValorTotal.getText()) + valorPizza));
        }
        
        PizzaVO pizzaVO = new PizzaVO();
        pizzaVO.setSabor((String)cbSabor1.getSelectedItem());
        
        PizzaRN pizzaRN = new PizzaRN();
        try{
            ArrayList<PizzaVO> pizza = pizzaRN.buscarPizza(pizzaVO);
            for(PizzaVO pizVO: pizza){
                String[] linha = {"" + pizVO.getCodigo(), ""
                             + sabor1 + ", " + sabor2 + ", " + sabor3, ""
                             + "1", ""
                             + valorPizza + ""};
                dtm.addRow(linha);
            }
            
        }catch(SQLException sql){
            
        }catch (Exception e){
            
        }

        BordaVO bordaVO = new BordaVO();
        bordaVO.setSabor((String)cbBorda.getSelectedItem());
        
        BordaRN bordaRN = new BordaRN();
        try{
            ArrayList<BordaVO> borda = bordaRN.buscarBorda(bordaVO);
            for(BordaVO borVO: borda){
                String[] linhaBorda = {"" + borVO.getCodigo(), ""
                             + borVO.getSabor(), ""
                             + "1", ""
                             + borVO.getPreco() + ""};
                dtm.addRow(linhaBorda);
                this.form.tValorTotal.setText(String.valueOf(Double.parseDouble(this.form.tValorTotal.getText()) + borVO.getPreco()));
            }
            
        }catch(SQLException sql){
            
        }catch (Exception e){
            
        }finally{
            this.dispose();
        }
    }//GEN-LAST:event_bAdicionarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void preencherCombo(){ 
        try{
            BordaVO bordaVO = new BordaVO();
            BordaRN bordaRN = new BordaRN();

            bordaVO.setCodigo(0);
            bordaVO.setStatus("Ativo");
            ArrayList<BordaVO> borda = bordaRN.buscarBorda(bordaVO);
            cbBorda.addItem("Selecione");
            for(BordaVO borVO: borda)
                cbBorda.addItem(borVO.getSabor());
            
            PizzaVO pizzaVO = new PizzaVO();
            PizzaRN pizzaRN = new PizzaRN();
            
            pizzaVO.setCodigo(0);
            pizzaVO.setStatus("Ativo");
            ArrayList<PizzaVO> pizza = pizzaRN.buscarPizza(pizzaVO);
            cbSabor1.addItem("Selecione");
            cbSabor2.addItem("Selecione");
            cbSabor3.addItem("Selecione");
            for(PizzaVO pizVO: pizza){
                cbSabor1.addItem(pizVO.getSabor());
                cbSabor2.addItem(pizVO.getSabor());
                cbSabor3.addItem(pizVO.getSabor());
            }
        }catch (SQLException sql){
        
        }catch (Exception e){
            
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdicionar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JComboBox<String> cbBorda;
    private javax.swing.JComboBox<String> cbSabor1;
    private javax.swing.JComboBox<String> cbSabor2;
    private javax.swing.JComboBox<String> cbSabor3;
    private javax.swing.JComboBox<String> cbTamanho;
    private javax.swing.JLabel lBorda;
    private javax.swing.JLabel lSabor1;
    private javax.swing.JLabel lSabor2;
    private javax.swing.JLabel lSabor3;
    private javax.swing.JLabel lTamanho;
    private javax.swing.JPanel pPedidoPizza;
    // End of variables declaration//GEN-END:variables
}
