/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import regraNegocio.BordaRN;
import vo.BordaVO;

/**
 *
 * @author Giovane
 */
public class PFormBorda extends TFormPesquisa implements ActionListener{

    /**
     * Creates new form PFormBorda
     */
    public PFormBorda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBorda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa Bordas");

        tbBorda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Sabor", "Tipo", "Preço", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbBorda);

        javax.swing.GroupLayout pCentroLayout = new javax.swing.GroupLayout(pCentro);
        pCentro.setLayout(pCentroLayout);
        pCentroLayout.setHorizontalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        pCentroLayout.setVerticalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pCentro, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void bPesquisarActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            BordaVO bordaVO = new BordaVO();
            
            if(!tCodigo.getText().isEmpty())
                bordaVO.setCodigo(Integer.parseInt(tCodigo.getText()));
            else bordaVO.setCodigo(0);
            
            if(!tDescricao.getText().isEmpty())
                bordaVO.setSabor((tDescricao.getText()));
            else bordaVO.setSabor(null);
            
            BordaRN bordaRN = new BordaRN();
            ArrayList<BordaVO> borda = bordaRN.buscarBorda(bordaVO);
            
            if(!borda.isEmpty()){
                javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tbBorda.getModel();
                dtm.fireTableDataChanged();
                dtm.setRowCount(0);

                for(BordaVO borVO : borda){
                    String[] linha = {"" + borVO.getCodigo(), "" 
                                         + borVO.getSabor(), "" 
                                         + borVO.getTipo(), "" 
                                         + borVO.getPreco(), "" + ""
                                         + borVO.getStatus(), ""};
                    dtm.addRow(linha);
                }
            }else
                JOptionPane.showMessageDialog(null, "Nenhum registro encontrado.", "Pesquisa de Bordas", JOptionPane.INFORMATION_MESSAGE);
            
        }catch (SQLException sql){
            JOptionPane.showMessageDialog(null, "Ocorreu um erro de SQL na pesquisa de bordas. Erro: " + sql, "Pesquisar Bordas", JOptionPane.ERROR_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ocorreu um erro na pesquisa de bordas. Erro: " + e, "Pesquisar Bordas", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    @Override
    public void bCadastrarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        CFormBorda cFormBorda = new CFormBorda();
        cFormBorda.setVisible(true);
    }
    
    @Override
    public void bEditarActionPerformed(java.awt.event.ActionEvent evt) {
        if(tbBorda.getSelectedRowCount() == 1){
            
            BordaVO bordaVO = new BordaVO();
            
            bordaVO.setCodigo(Integer.parseInt((String) tbBorda.getValueAt(tbBorda.getSelectedRow(), 0)));
            bordaVO.setSabor((String) tbBorda.getValueAt(tbBorda.getSelectedRow(), 1));
            bordaVO.setTipo((String) tbBorda.getValueAt(tbBorda.getSelectedRow(), 2));
            bordaVO.setPreco(Double.parseDouble((String) tbBorda.getValueAt(tbBorda.getSelectedRow(), 3)));
            bordaVO.setStatus((String) tbBorda.getValueAt(tbBorda.getSelectedRow(), 4));
            
            CFormBorda cFormBorda = new CFormBorda(bordaVO);
            cFormBorda.setVisible(true);
        }else
            JOptionPane.showMessageDialog(null, "Selecione uma borda para editar.", "Edição de Borda", JOptionPane.INFORMATION_MESSAGE);
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pCentro;
    private javax.swing.JTable tbBorda;
    // End of variables declaration//GEN-END:variables
}
