/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import regraNegocio.ArquivoRN;
import regraNegocio.PedidoRN;
import vo.RelatorioVO;

/**
 *
 * @author Giovane
 */
public class RFormRelatorioPedidoPorPeriodo extends javax.swing.JFrame {

    /**
     * Creates new form RFormRelatrioPedidoPorPeriodo
     */
    public RFormRelatorioPedidoPorPeriodo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNorte = new javax.swing.JPanel();
        lDatInicial = new javax.swing.JLabel();
        lDataFinal = new javax.swing.JLabel();
        bPesquisar = new javax.swing.JButton();
        dtInicial = new com.toedter.calendar.JDateChooser();
        dtFinal = new com.toedter.calendar.JDateChooser();
        pSul = new javax.swing.JPanel();
        bGerar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        pCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPedidoPeriodo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lDatInicial.setText("Data Inicial:");

        lDataFinal.setText("Data Final:");

        bPesquisar.setText("Pesquisar");
        bPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pNorteLayout = new javax.swing.GroupLayout(pNorte);
        pNorte.setLayout(pNorteLayout);
        pNorteLayout.setHorizontalGroup(
            pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorteLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNorteLayout.createSequentialGroup()
                        .addComponent(lDatInicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(lDataFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNorteLayout.createSequentialGroup()
                        .addComponent(bPesquisar)
                        .addGap(208, 208, 208))))
        );
        pNorteLayout.setVerticalGroup(
            pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDatInicial)
                    .addComponent(lDataFinal)
                    .addComponent(dtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(bPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pNorte, java.awt.BorderLayout.NORTH);

        bGerar.setText("Gerar Relatório");
        bGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSulLayout = new javax.swing.GroupLayout(pSul);
        pSul.setLayout(pSulLayout);
        pSulLayout.setHorizontalGroup(
            pSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pSulLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(bGerar)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        pSulLayout.setVerticalGroup(
            pSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSulLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bGerar)
                .addContainerGap())
        );

        getContentPane().add(pSul, java.awt.BorderLayout.SOUTH);

        tbPedidoPeriodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Descrição", "Data", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbPedidoPeriodo);

        javax.swing.GroupLayout pCentroLayout = new javax.swing.GroupLayout(pCentro);
        pCentro.setLayout(pCentroLayout);
        pCentroLayout.setHorizontalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );
        pCentroLayout.setVerticalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pCentro, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisarActionPerformed
        RelatorioVO relatorioVO = new RelatorioVO();
        try{
            if(!dtInicial.getDate().toString().isEmpty() && !dtFinal.getDate().toString().isEmpty()){
                relatorioVO.setDataI(dtInicial.getDate());
                relatorioVO.setDataF(dtFinal.getDate());

                PedidoRN pedidoRN = new PedidoRN();
                ArrayList<RelatorioVO> dadosRelatorio = pedidoRN.gerarRelatorioPeriodo(relatorioVO);
                
                javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tbPedidoPeriodo.getModel();
                dtm.fireTableDataChanged();
                dtm.setRowCount(0);
                
                for(RelatorioVO relVO : dadosRelatorio){
                    String[] linha = {"" + relVO.getCliente(), "" 
                                         + relVO.getDescricao(), "" 
                                         + relVO.getDataI(), "" + ""
                                         + relVO.getPreco(), ""};
                    dtm.addRow(linha);
                }
            }else JOptionPane.showMessageDialog(null, "É necessário informar o período para gerar o relatório.");
        }catch(SQLException sql){
            JOptionPane.showMessageDialog(null, "Ocorreu um erro de SQL ao buscar os dados do relatório. Erro: " + sql, "Gerar relatório por período", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao buscar os dados do relatório. Erro: " + e, "Gerar relatório por período", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bPesquisarActionPerformed

    private void bGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGerarActionPerformed
        ArquivoRN arquivo = new ArquivoRN();
        arquivo.gerarRelatorioPorPeriodo(this);
        
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tbPedidoPeriodo.getModel();
        dtm.fireTableDataChanged();
        dtm.setRowCount(0);
    }//GEN-LAST:event_bGerarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGerar;
    private javax.swing.JButton bPesquisar;
    private com.toedter.calendar.JDateChooser dtFinal;
    private com.toedter.calendar.JDateChooser dtInicial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lDatInicial;
    private javax.swing.JLabel lDataFinal;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pNorte;
    private javax.swing.JPanel pSul;
    public javax.swing.JTable tbPedidoPeriodo;
    // End of variables declaration//GEN-END:variables
}
